const projects = [
  {company:'Solana',title:'Implications of Alpenglow on Staking and Liquid Staking',desc:'An assessment of what the Alpenglow consensus mechanism changes for staking, validators and liquid-staking protocols.',tags:['Consensus','Staking','Research'],url:'https://docs.google.com/document/d/198fvEcQyS9GKdcvUw14TRT6wTXDGB_uNlKeECTjWtY8/edit?usp=sharing'},
  {company:'Solblaze',title:'Liquid Staking on Solana',desc:'A technical field guide to the SolBlaze ecosystem, its liquid-staking model and growing suite of products.',tags:['Solana','DeFi','Technical'],url:'https://drive.google.com/file/d/1-6qoED6N8ZugmRi01mVfj05FAA1A8-LP/view'},
  {company:'Digital Asset Treasuries',title:'Modern Empires Built on Crypto',desc:'A research-led look at the emergence of digital-asset treasuries and the new balance sheets they create.',tags:['Markets','Strategy','Research'],url:'https://drive.google.com/file/d/14WHGKS3Pb9sw2AvnIiOkkPTzVFtLyvEw/view'},
  {company:'Etherfuse',title:'Stablebonds: Transforming Collateral in DeFi',desc:'How tokenised sovereign debt can become productive, dependable collateral for onchain finance.',tags:['Stablebonds','DeFi','Explainer'],url:'https://open.substack.com/pub/outstandingvick/p/how-etherfuse-stablebonds-are-redefining'},
  {company:'Solana Collective',title:'The Silent Content Revolution',desc:'A case for content as Web3 infrastructure: the layer that turns technology into culture, trust and adoption.',tags:['Culture','Content','Opinion'],url:'https://open.substack.com/pub/outstandingvick/p/the-silent-revolution-why-content'},
  {company:'Busha',title:'Busha’s Solana-backed Loans',desc:'An examination of how Busha is using Solana rails to unlock liquidity without forcing holders to sell.',tags:['Lending','Solana','Analysis'],url:'https://open.substack.com/pub/outstandingvick/p/bushas-solana-backed-loans-liquidity'}
];
export default function Works(){return <section className="section-block section-rule" id="works"><div className="section-meta"><span>The Evidence</span><span>Exhibits A–F · Entered 2025–Now</span></div><div className="section-heading"><span>Selected</span><h2>Field Reports</h2></div><div className="works-grid">{projects.map((p,i)=><article className="work-card" key={p.title}><div className="exhibit"><span>Exhibit {String.fromCharCode(65+i)}</span><span>Verified</span></div><p className="company">{p.company}</p><h3>{p.title}</h3><p className="work-desc">{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a href={p.url} target="_blank" rel="noreferrer">Open report →</a></article>)}</div></section>}
